export enum ErrorTypes {
    NOT_ACTIVATED_ACCOUNT = "NOT_ACTIVATED_ACCOUNT",
    EXISTING_USER = "EXISTING_USER",
    INPUT_VALIDATION_ERROR = "INPUT_VALIDATION_ERROR",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    NOT_FOUND = "NOT_FOUND",
    NOT_AUTHERIZED = "NOT_AUTHERIZED",
    ALREADY_ACTIVATED_ACCOUNT = "ALREADY_ACTIVATED_ACCOUNT",
    BAD_REQUEST = "BAD_REQUEST"
};